### ISSUE TITLE
Vsphere target is failing with datacenter 

### ISSUE THREAD

**Issue by amedisetti** [nanovms/ops#578]
I set GOVC_URL, GOVC_DATACENTER,
When i run : ops image create -c config.json -t vsphere -a gtest, it is failing with:
Please specify datacenter 

I am following example given in doc.

**Comment by eyberg** [comment]
GOVC_DATACENTER looks hardcoded in a few places

idk if you have the govc cli tools https://github.com/vmware/govmomi/tree/master/govc  installed? but if you run

```
govc datacenter.info
```

does that give you something different than the default of 'ha-datacenter'?

I believe changing this might alleviate that

https://github.com/nanovms/ops/blob/master/lepton/vsphere.go#L82-L98

**Comment by amedisetti** [comment]
Yes I have checked GOVC datacenter.info, I have different datacenter.

I do see that default dc has set as highlighted in vsphere.go, but there is env variable set above the default value. 
Why is it not overwriting ?

I m thinking may be login url need to change ?
It suppose to take username /password env variables.

**Comment by eyberg** [comment]
@amedisetti the env var was not actually being used - there were a few places it was hardcoded - are you able to build the go code && see if that fixes it for you?

**Comment by amedisetti** [comment]
Yes I can do  , could you tell me where would I change  to make env  Variables work ?

I see if statement , if dc !# null , set v.datacenter = dc, not sure why doesn’t work .

**Comment by eyberg** [comment]
@amedisetti yes - the GOVC_URL takes a login and password and they should be url-encoded - so if your password has a special character for instance it needs to have it set - ```govc about``` should work if the GOVC_URL is set correctly

if you can build the go from src I just merged in this fix https://github.com/nanovms/ops/pull/579 to un-stub the datacenter which can be set like this from env var (if you wanted to create something) ->

```
#!/bin/sh

export GOVC_INSECURE=1
export GOVC_URL="login:pass@127.0.0.1:443"
export GOVC_DATACENTER="/ha-datacenter/"

GOOS=linux go build -o gtest

ops image create -c config.json -t vsphere -a gtest
```

**Comment by amedisetti** [comment]
I m still getting same error:
Please specify datacenter.

I have tried govc about with your url syntax , it is giving error. I think we need add GOVC_USERNAME and GOVC_PASSWORD to  support env.

Url syntax seems wrong .

**Comment by eyberg** [comment]
i'm ok w/adding support for the GOVC_USERNAME/GOVC_PASSWORD method (which we don't have support for today) but specifying the creds in the url should work fine (again might need to check your l/p for special characters that might need to be encoded) - this should work with govc by itself

what version of vsphere are you using? can you verify that your auth works w/just govc?

**Comment by amedisetti** [comment]
If I export username and password, govc about works fine.
But doesn’t work with url syntax.
I have put %40 for special characters, it works.

Version :6.5
