### ISSUE TITLE
Issues Creating a Local Dev Package: Dartlang v2.10.4

### ISSUE THREAD

**Issue by FredrikBakken** [nanovms/ops#813]
Hello! I am currently working my way through the documentation and was trying to create a new local development package containing [Dartlang v2.10.4](https://dart.dev/tools/sdk/archive), but I seem to be running into a lot of error messages.

I used the following links as reference points for building the package:
- https://nanovms.gitbook.io/ops/packages#creating-a-custom-or-local-dev-packages
- https://github.com/nanovms/ops/blob/master/PACKAGES.md

My steps for creating the package were as follows:

1. Create a new directory: `mkdir dart_2.10.4`
2. Add the `dart` binary from the downloaded dartsdk-linux-x64-release.zip (found in `dart-sdk/bin`)
3. Create a `package.manifest` file:
```
{
    "Program": "dart_2.10.4/dart",
    "Args": ["dart"],
    "Version": "2.10.4"
}
```

4. Use `ldd dart` to find the shared libraries and copy these over to sub-folders within `dart_2.10.4/sysroot`:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs$ ldd dart_2.10.4/dart
        linux-vdso.so.1 (0x00007ffcbd9e6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe5392d9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe5392b7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe539168000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe538f7e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe53b661000)
```

5. My tree structure now looks like this:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs$ tree dart_2.10.4
dart_2.10.4
├── dart
├── package.manifest
└── sysroot
    ├── lib
    │   └── x86_64-linux-gnu
    │       ├── libc.so.6
    │       ├── libdl.so.2
    │       ├── libm.so.6
    │       ├── libnss_dns.so.2
    │       ├── libpthread.so.0
    │       └── libresolv.so.2
    └── lib64
        └── ld-linux-x86-64.so.2

4 directories, 9 files
```

6. Copy the `dart_2.10.4` directory to ~/.ops/local_packages: `cp -r ./dart_2.10.4 ~/.ops/local_packages/dart_2.10.4/`
7. Create an example application (`main.dart`):
```
void main() {
	print("Hello world!");
}
```

8. Use `ops` with the local `dart_2.10.4` package to run the example file: `ops load -l dart_2.10.4 -a main.dart`

The error message I keep running into:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs$ ops load -l dart_2.10.4 -a main.dart -v
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
qemu-system-x86_64 -machine q35 -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x3 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x3.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x3.0x2 -device virtio-scsi-pci,bus=pci.2,addr=0x0,id=scsi0 -device scsi-hd,bus=scsi0.0,drive=hd0 -machine accel=kvm:tcg -cpu host -no-reboot -cpu max -machine q35 -device isa-debug-exit -m 2G -drive file=/home/fredrikbakken/.ops/images/dart.img,format=raw,if=none,id=hd0 -device virtio-net,bus=pci.3,addr=0x0,netdev=n0 -netdev user,id=n0 -display none -serial stdio
assigned: 10.0.2.15
dispatch_signals error: signal 11 resulting in core dump
unimplemented signal
ffffffff80014726        (kern_unlock + 0000000000000056/0000000000000070)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff800513f7        (dispatch_signals + 0000000000000587/00000000000005ef)
ffffffff800633f5        (run_thread + 0000000000000015/000000000000001d)
ffffffff80014a7f        (runloop_internal + 000000000000030f/0000000000000492)
assertion l->w == 1 failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/lock.h: spin_unlock() on line 40; halt
ffffffff80014726        (kern_unlock + 0000000000000056/0000000000000070)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff80014740        (kernel_sleep + 0000000000000000/0000000000000024)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff800513f7        (dispatch_signals + 0000000000000587/00000000000005ef)
ffffffff800633f5        (run_thread + 0000000000000015/000000000000001d)
ffffffff80014a7f        (runloop_internal + 000000000000030f/0000000000000492)
assertion l->w == 1 failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/lock.h: spin_unlock() on line 40; halt
ffffffff80014726        (kern_unlock + 0000000000000056/0000000000000070)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff80014740        (kernel_sleep + 0000000000000000/0000000000000024)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff80014740        (kernel_sleep + 0000000000000000/0000000000000024)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff800513f7        (dispatch_signals + 0000000000000587/00000000000005ef)
ffffffff800633f5        (run_thread + 0000000000000015/000000000000001d)
ffffffff80014a7f        (runloop_internal + 000000000000030f/0000000000000492)
...
frame trace:

frame ffff8000014a0000 already full
cpu 0000000000000000, state user, vector 000000000000000e
 interrupt: 000000000000000e (Page fault)
     frame: ffff8000014a0000
error code: 0000000000000002
   address: ffff8000014a7ff8

   rax: 2248959df8b61a5c
   rbx: ffff8000014a8030
   rcx: 00000000000003d5
   rdx: ffff8000014a7fc0
   rsi: 0000000000000008
   rdi: ffff8000014a8030
   rbp: ffff8000014a8000
   rsp: ffff8000014a7fc0
    r8: 000000000000004d
    r9: 00000000000003d5
   r10: 0000000000001f90
   r11: 00000000000bbf20
   r12: 0000000000000010
   r13: ffffffff800adbbc
   r14: ffffffff800adbbc
   r15: ffff800001480150
   rip: ffffffff8008a438        (validate_virtual + 0000000000000018/0000000000000057)
rflags: 0000000000010086
    ss: 0000000000000000
    cs: 0000000000000008
    ds: 0000000000000000
    es: 0000000000000000
fsbase: 0000000000000000
gsbase: 0000000000000000
...
```

Are there any obvious mistakes I have made while setting up this local package?

**Comment by eyberg** [comment]
I was able to do a quick POC with ```ops run``` via this ->

````
eyberg@box:~/d2$ ops run -c config.json dart-sdk/bin/dart
[dart main.dart]
booting /home/eyberg/.ops/images/dart.img ...
assigned: 10.0.2.15
Hello world!

^Csignal: killed
eyberg@dungeon:~/d2$ cat config.json
{
  "Args": ["dart", "main.dart"],
  "Dirs": ["dart-sdk"],
  "Files": ["main.dart"]
}
```

although for some reason it doesn't want to hang up - not sure what's going on there

however, I noticed there is an AOT compile option which might be a better fit since it sidesteps the package and considering it'll be faster too?

```
eyberg@box:~/d2$ dart-sdk/bin/dart2native main.dart
Generated: /home/eyberg/d2/main.exe
eyberg@box:~/d2$ ls
config.json  dart-sdk  dartsdk-linux-x64-release.zip  main.dart  main.exe
eyberg@box:~/d2$ file main.exe
main.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
eyberg@box:~/d2$ ops run main.exe
booting /home/eyberg/.ops/images/main.exe.img ...
assigned: 10.0.2.15
Hello world!
exit status 1
```

i'll look into the pkg here in a bit regardless

**Comment by FredrikBakken** [comment]
Thank you for the quick response, @eyberg! I completely agree with you that an AOT-compilation is recommended. I tried to replicate your steps to see if I would be able to reproduce your successful run, but I have unfortunately stumbled upon the same error messages. See below for my replicated steps:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ dart-sdk/bin/dart2native main.dart
Generated: /home/fredrikbakken/Documents/github/unikernels/pkgs/ex/main.exe
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ls
config.json  dart-sdk  main.dart  main.exe
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ file main.exe 
main.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ cat config.json 
{
  "Args": ["dart", "main.dart"],
  "Dirs": ["dart-sdk"],
  "Files": ["main.dart"]
}
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ops run -c config.json dart-sdk/bin/dart
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
assigned: 10.0.2.15
dispatch_signals error: signal 11 resulting in core dump
unimplemented signal
ffffffff80014726        (kern_unlock + 0000000000000056/0000000000000070)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff800513f7        (dispatch_signals + 0000000000000587/00000000000005ef)
ffffffff800633f5        (run_thread + 0000000000000015/000000000000001d)
ffffffff80014a7f        (runloop_internal + 000000000000030f/0000000000000492)
assertion l->w == 1 failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/lock.h: spin_unlock() on line 40; halt
ffffffff80014726        (kern_unlock + 0000000000000056/0000000000000070)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff80014740        (kernel_sleep + 0000000000000000/0000000000000024)
ffffffff80003296        (kernel_shutdown + 0000000000000066/0000000000000074)
ffffffff8000b56e        (halt + 00000000000000de/00000000000000e2)
ffffffff800513f7        (dispatch_signals + 0000000000000587/00000000000005ef)
ffffffff800633f5        (run_thread + 0000000000000015/000000000000001d)
ffffffff80014a7f        (runloop_internal + 000000000000030f/0000000000000492)
assertion l->w == 1 failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/lock.h: spin_unlock() on line 40; halt
...
```

I have also made sure to remove the local_package build in case it would interfere with the process.

In case it helps for the debugging, I am running on the latest version of Pop OS (20.10) with the following versions of Ops/Nanos:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ops version
Ops version: 0.1.14
Nanos version: 0.1.29
```

**Comment by eyberg** [comment]
* so you were able to run the AOT generated binary fine? you're having trouble w/normal ops run though? (i noticed w/run it's pretty slow)

* if you want to try w/nightly 'ops run -n' to see if that fixes the run issue for you

* we'll have @francescolavra look into the pkg issue as I ran into problems there

**Comment by eyberg** [comment]
also - this looks related -> https://github.com/nanovms/nanos/pull/1350 (although that would just be noise)

**Comment by FredrikBakken** [comment]
I double-checked with the `dart2native` documentation on the Dart website: https://dart.dev/tools/dart2native#creating-aot-snapshots to make sure that the AOT-file is created correct:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ dart-sdk/bin/dart2native main.dart -k aot
Generated: /home/fredrikbakken/Documents/github/unikernels/pkgs/ex/main.aot
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ file main.aot
main.aot: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=409a65056ca7b2b84a33d6a1c27907a8, with debug_info, not stripped
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ dart-sdk/bin/dartaotruntime main.aot
Hello world!
```

I then updated the `config.json` to fit with the AOT execution:
```
{
  "Args": ["dartaotruntime", "main.aot"],
  "Dirs": ["dart-sdk"],
  "Files": ["main.aot"]
}
```

Running the following two `ops run` commands results in the same error as mentioned before:
- `$ ops run -n -c config.json dart-sdk/bin/dart`
- `$ ops run -c config.json dart-sdk/bin/dart`

I also made sure that `ops run` works well in other cases, such as in the Getting Started [examples](https://nanovms.gitbook.io/ops/basic_usage#running-golang-hello-world).

**Comment by eyberg** [comment]
can you just run the stand-alone exe by itself (and not the snapshot?) - that doesn't the runtime cause it includes it

```
dart-sdk/bin/dart2native main.dart
```

**Comment by FredrikBakken** [comment]
Running only the standalone `.exe` results in the following:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ dart-sdk/bin/dart2native main.dart
Generated: /home/fredrikbakken/Documents/github/unikernels/pkgs/ex/main.exe
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ file main.exe
main.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ./main.exe 
Hello world!
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ops run -n main.exe
booting /home/fredrikbakken/.ops/images/main.exe.img ...
assigned: 10.0.2.15
dispatch_signals error: signal 11 resulting in core dump
unimplemented signal
ffffffff8000344a        (kernel_shutdown + 000000000000006a/00000000000000ba)
ffffffff8000b67c
ffffffff8004ccab        (dispatch_signals.part.46 + 00000000000003fb/0000000000000421)
ffffffff8005fcf5        (run_thread + 0000000000000015/000000000000001d)
ffffffff8001365d        (runloop_internal + 000000000000021d/000000000000049b)
assertion l->w == 1 failed in /home/circleci/project/src/x86_64/lock.h: spin_unlock() on line 38; halt
```

Same error when using: `ops run main.exe`.

**Comment by eyberg** [comment]
the kernel_shutdown stuff should be fixed in nightly branch of nanos (and i believe 0.1.30) but that is prob just noise - you prob. still get that segfault

**Comment by FredrikBakken** [comment]
@eyberg, you are correct. The issue seems to be persistent on my laptop. However, I tried to experiment a little by using Virutalbox and Ubuntu 18.04. I am now able to run without any issues:
```
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ ls
config.json  dart-sdk  main.dart
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ ops run -c config.json dart-sdk/bin/dart
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false
 
assigned: 10.0.2.15
Hello world!
```

Using `ops run main.exe` also seems to be working without any issues:
```
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ dart-sdk/bin/dart2native main.dart
Generated: /home/fredrikbakken/Documents/unikernel/da/main.exe
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ ls
config.json  dart-sdk  main.dart  main.exe
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ file main.exe main.exe: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped
fredrikbakken@fredrikbakken-VirtualBox:~/Documents/unikernel/da$ ops run main.exe
booting /home/fredrikbakken/.ops/images/main.exe.img ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false
 
assigned: 10.0.2.15
Hello world!
exit status 1
```

I am not sure why it does not work on my local Pop! OS 20.10. I will continue to dig around a little on it when I have time to do so.

**Comment by FredrikBakken** [comment]
I suspect that I might start to be on to something as I just encountered the same error message on a clean installed Pop! OS 20.10 in VirtualBox, as I encounter on my locally installed OS:
```
fredrikbakken@pop-os:~/Documents/unikernels/da$ ls
config.json  dart-sdk  main.dart
fredrikbakken@pop-os:~/Documents/unikernels/da$ ops run -c config.json dart-sdk/bin/dart
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false
 
assigned: 10.0.2.15
signal 11 received by tid 1, errno 0, code 128
   fault address 0x0
   core dump (unimplemented)
exit status 255
```

Looking into the installation process on Pop! OS 20.10 and Ubuntu 18.04, the only difference I can see is the following:
- Pop! OS 20.10: `sudo apt install qemu-system-x86`
- Ubuntu 18.04: `sudo apt install qemu`

The Pop! OS qemu installation was used as I encounter the same issue as described in #525.

Running `ops profile` returns the following:
- Pop! OS 20.10:
```
fredrikbakken@pop-os:~$ ops profile
Ops version: 0.1.15
Nanos version: 0.1.30
Qemu version: 5.0.0
Arch: linux
Virtualized: false
```

- Ubuntu 18.04:
```
fredrikbakken@fredrikbakken-VirtualBox:~$ ops profile
Ops version: 0.1.15
Nanos version: 0.1.30
Qemu version: 2.11.1
Arch: linux
Virtualized: true
```

**Comment by eyberg** [comment]
can you run w/tracing enabled, verbosity, and accel disabled?

 ```ops run -v -c config.json dart-sdk/bin/dart --accel=false --trace```

**Comment by FredrikBakken** [comment]
Running the following `ops run -v -c config.json dart-sdk/bin/dart --accel=false --trace` results in:
```
fredrikbakken@pop-os:~/Documents/github/unikernels/pkgs/ex$ ops run -v -c config.json dart-sdk/bin/dart --accel=false --trace
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
You have disabled hardware acceleration

qemu-system-x86_64 -machine q35 -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x3 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x3.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x3.0x2 -device virtio-scsi-pci,bus=pci.2,addr=0x0,id=scsi0 -device scsi-hd,bus=scsi0.0,drive=hd0 -no-reboot -cpu max -smp 1 -machine q35 -device isa-debug-exit -m 2G -drive file=/home/fredrikbakken/.ops/images/dart.img,format=raw,if=none,id=hd0 -device virtio-net,bus=pci.3,addr=0x0,netdev=n0 -netdev user,id=n0 -display none -serial stdio
assigned: 10.0.2.15
read program complete: 0xffff810000000000 gitversion: ff2409413769a2fd194030b7c30eb39654874d3b 1 run thread, cpu 0, frame 0xffff800002601000, rip 0x2000010d0, rsp 0x7fdf9ec0, rdi 0x0, rax 0x0, rflags 0x200, cs 0x2b, sysret
1 brk
1 direct return: 44113920, rsp 0x7fdf9d98
1 run thread, cpu 0, frame 0xffff800002601000, rip 0x20001ec6b, rsp 0x7fdf9d98, rdi 0x0, rax 0x2a12000, rflags 0x246, cs 0x2b, sysret
1 arch_prctl
1 arch_prctl: code 0x3001, addr 0x7fdf9df0
1 direct return: -22, rsp 0x7fdf9da0
1 run thread, cpu 0, frame 0xffff800002601000, rip 0x20001d1ea, rsp 0x7fdf9da0, rdi 0x3001, rax 0xffffffffffffffea, rflags 0x246, cs 0x2b, sysret
1 general protection fault in user mode, rip 0x2000033d1
1 delivering SIGSEGV to thread 1; vaddr 0x0 si_code 128
1 signal 11 received, errno 0, code 128

1    fault address 0x0

1    default action

signal 11 received by tid 1, errno 0, code 128
   fault address 0x0
1    core dump (unimplemented)

   core dump (unimplemented)
exit status 255
```

**Comment by FredrikBakken** [comment]
I just tried to same setup on Ubuntu 20.10 (in Virtualbox). This version also requires the installation of `sudo apt install qemu-system-x86`, and results in the same error message as found in Pop! OS 20.10.

**Comment by eyberg** [comment]
@FredrikBakken I updated an instance to ubuntu groovy (which matches your pop os) and I can now reproduce this w/ qemu 5.0.0 - we'll take a look at it

**Comment by sanderssj** [comment]
The program is crashing in the interpreter responsible for loading shared libraries for a program, in the case of Ubuntu groovy is /lib/x86_64-linux-gnu/ld-2.32.so. Apparently this version of that library has a small disagreement between the size of the bss reflected in the elf header and what library actually uses. Probably any dynamically linked program with extra libraries would have this problem running on nanos with this particular version of ld.
I will have a PR with a fix shortly.

**Comment by sanderssj** [comment]
Correction, this is part of the loader's behavior which uses the unused space in the same page as the bss for a little malloc.

**Comment by sanderssj** [comment]
Fixed by https://github.com/nanovms/nanos/pull/1355

**Comment by eyberg** [comment]
@FredrikBakken you should be able to run this w/the nightly branch now w/ 'ops run -n'

**Comment by FredrikBakken** [comment]
@eyberg and @sanderssj, thank you both for this amazing and quick support! I have been able to run the simple helloworld `.dart` application with the latest nightly build.

I am however still experiencing some issues when I try to create a local `dart_2.10.4` package. The error message I get when I try to load this local package is as follows:
```
ops load -n -l dart_2.10.4 -a main.dart
[dart main.dart]
booting /home/fredrikbakken/.ops/images/dart.img ...
assigned: 10.0.2.15
Inconsistency detected by ld.so: ../sysdeps/unix/sysv/linux/dl-origin.c: 46: _dl_get_origin: Assertion `linkval[0] == '/'' failed!
exit status 255
```

This was found on Pop OS 20.10.

Sorry for the late reply, been a busy last week at work before Christmas.

**Comment by sanderssj** [comment]
Hi @FredrikBakken --
I'll have a fix for this shortly, but for now you can work around it by modifying your dart_2.10.4 package.manifest to include a '/' at the beginning of the dart path, like so:
`"Program": "/dart_2.10.4/dart"`

Glibc just wants to have an absolute executable path, hence the assertion that the first character is a '/'.

**Comment by FredrikBakken** [comment]
Hi @sanderssj!
Thank you so much for the fast reply. Your quick-fix seems to work perfectly to solve the last problem I have been facing. Closing this issue as it seems to be fixed from my point of view.
